site:
  title: Linuxgoose's AsciiDoc Sandbox
  url: https://www.jordanrobinson.org/asciidoc-sandbox/
  start_page: home::index.adoc
  robots: |
    User-agent: *
    Allow: /
git:
  ensure_git_suffix: false
  fetch_concurrency: 1
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  sources:
  - url: .
    branches: main
    start_path: home
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./build/site
runtime:
  fetch: true